name: juliotati
description: "Júlio Tati is a curious being interested in the human mind. As for what he spends his on, he helps translate and transform ideas to usable products in form of well engineered software."

version: 0.1.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter

  flutter_gen: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  google_fonts: ^6.2.0
  http: ^1.2.1
  intl: ^0.19.0
  link_target: ^0.1.1
  logger: ^2.4.0
  provider: ^6.1.2
  url_launcher: ^6.2.5
  url_strategy: ^0.3.0

flutter_intl:
  enabled: true
  class_name: AppLocal
  main_locale: en
  arb_dir: lib/translations
  output_dir: lib/translations

dev_dependencies:
  build_runner: ^2.4.8
  build_version: ^2.1.1
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  go_router_builder: ^2.4.1
  lint: ^2.3.0
flutter:
  assets:
    - assets/cars/
    - assets/app_images/

  uses-material-design: true
