name: juliotati
description: "Meet Júlio Tati—a seeker intrigued by the labyrinth of the human mind. He dedicates his time to a unique alchemy: translating fleeting thoughts into tangible reality. Through the refined craft of software engineering, he shapes ideas into polished products that seamlessly integrate into our daily lives. His is the silent magic of innovation, transforming the abstract into the indispensable."

version: 0.1.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter

  flutter_gen: ^5.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  google_fonts: ^6.2.0
  http: ^1.2.1
  intl: ^0.19.0
  link_target: ^0.1.2
  logger: ^2.4.0
  provider: ^6.1.2
  url_launcher: ^6.2.5
  url_strategy: ^0.3.0
  web: ^1.0.0

flutter_intl:
  enabled: true
  class_name: AppLocal
  main_locale: en
  arb_dir: lib/translations
  output_dir: lib/translations

dev_dependencies:
  build_runner: ^2.4.8
  build_version: ^2.1.1
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  go_router_builder: ^2.4.1
  lint: ^2.3.0
flutter:
  assets:
    - assets/cars/
    - assets/app_images/

  uses-material-design: true
