name: Web deployments
on:
  workflow_call:
    inputs:
      flutterVersion:
        required: true
        type: string
        default: '3.24.1'
        description: 'The version of Flutter to use for the workflow run'
      renderer:
        required: false
        type: string
        default: 'wasm'
        options: [ 'wasm', 'html', 'canvaskit', 'auto' ]
        description: 'The renderer to use for the workflow run'
      repoToken:
        required: true
        type: string
        description: 'Your repos GitHub token'
      firebaseServiceAccount:
        required: true
        type: string
        description: 'Projects Firebase service account'
      projectId:
        required: true
        type: string
        description: 'Your Firebase project ID'

jobs:
  build-and-deploy:
    runs-on: macos-latest
    env:
      FLUTTER_VERSION: '${{ inputs.flutterVersion }}'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-macos-stable-$FLUTTER_VERSION-x64'
          cache-path: '${{ runner.tool_cache }}/flutter-macos-stable-$FLUTTER_VERSION-x64-hash'
          channel: 'stable'
          flutter-version: $FLUTTER_VERSION
      - name: build-web
        run: |
          flutter pub get

          if [ "${{ inputs.renderer }}" != "--wasm" ]; then
            echo "Building web with: ${{ inputs.renderer }}"
            flutter build web --release --web-renderer ${{ inputs.renderer }}
          else
            echo "Building web with wasm"
            flutter build web --wasm
          fi

      - name: Install-firebase-tools
        uses: actions/setup-node@v4
        with:
          node-version: "21.2.0"
      - run: npm install -g firebase-tools@11.0.1
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ inputs.repoToken }}'
          firebaseServiceAccount: '${{ inputs.firebaseServiceAccount }}'
          channelId: live
          projectId: ${{ inputs.projectId }}
