name: 🚀 Deploy Júlio Tati
on:
  push:
    paths:
      - 'lib/**'
      - 'scripts/all_functions.sh'
      - '.github/workflows/app_cd_web.yml'
      - 'pubspec.yaml'
    branches:
      - main
      - test-pipelines

  workflow_dispatch:

jobs:
  sort-intl-file-contents:
    uses: Juliotati/juliotati_app/.github/workflows/sort_intl_json.yml@test-pipelines

  build-and-deploy-old:
    needs:
      - sort-intl-file-contents
    strategy:
      matrix:
        target: [ production ]
    uses: Juliotati/juliotati_app/.github/workflows/release_web.yml@test-pipelines
    with:
      target: ${{ matrix.target }}
      flutterVersion: '3.24.1'
      projectId: 'juliotatiapp'
    secrets:
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JULIOTATIAPP }}
      repoToken: ${{ secrets.GITHUB_TOKEN }}
