name: 🚀 Deploy Júlio Tati
on:
  push:
    paths:
      - '.github/workflows/app_cd_web.yml'
      - 'assets/**'
      - 'lib/**'
      - 'pubspec.yaml'
    branches:
      - main

  workflow_dispatch:

jobs:
  sort-intl-file-contents:
    uses: Juliotati/juliotati.com/.github/workflows/sort_intl_json.yml@main

  build-and-deploy:
    needs:
      - sort-intl-file-contents
    uses: Juliotati/juliotati.com/.github/workflows/cd_web.yml@main
    with:
      useWasm: false
      target: 'production'
      projectId: 'juliotatiapp'
    secrets:
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JULIOTATIAPP }}
      repoToken: ${{ secrets.GITHUB_TOKEN }}
