name: 🚀 Deploy Júlio Tati
on:
  push:
    paths:
      - 'lib/**'
      - 'scripts/all_functions.sh'
      - '.github/workflows/app_cd_web.yml'
      - 'pubspec.yaml'
    branches:
      - main

  workflow_dispatch:

jobs:
  sort-intl-file-contents:
    uses: Juliotati/juliotati_app/.github/workflows/sort_intl_json.yml@main

  build-and-deploy:
    needs:
      - sort-intl-file-contents
    strategy:
      matrix:
        target: [ production ]
    uses: Juliotati/juliotati_app/.github/workflows/cd_web.yml@main
    with:
      renderer: 'canvaskit'
      target: ${{ matrix.target }}
      projectId: 'juliotatiapp'
    secrets:
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JULIOTATIAPP }}
      repoToken: ${{ secrets.GITHUB_TOKEN }}
