name: Web deployments
on:
  push:
    branches:
      - release

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-macos-stable-3.24.0-x64'
          cache-path: '${{ runner.tool_cache }}/flutter-macos-stable-3.24.0-x64-hash'
          channel: 'stable'
          flutter-version: '3.24.0'
      - name: build web release canvaskit
        run: |
          flutter pub get
          flutter build web --release --wasm

      - name: Install firebase tools
        uses: actions/setup-node@v4
        with:
          node-version: "21.2.0"
      - run: npm install -g firebase-tools@11.0.1
        # Apparently this alone authenticates & deploys to firebase with --hosting only flag
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JULIOTATIAPP }}'
          channelId: live
          projectId: juliotatiapp
