name: Web deployments
on:
  push:
    paths:
      - 'lib/**'
      - '.github/workflows/cd_release_web.yml'
      - 'pubspec.yaml'
    branches:
      - main

  workflow_dispatch:

jobs:
  sort-translations-file-content:
    runs-on: macos-latest
    steps:
      - name: setup-repo
        uses: actions/checkout@v4
      - name: verify-config-existence-and-content
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/functions.sh"
          chmod +x "${GITHUB_WORKSPACE}/scripts/sort_translations_file_content.sh"
          bash "${GITHUB_WORKSPACE}/scripts/sort_translations_file_content.sh"

  build-and-deploy:
    needs:
      - sort-translations-file-content
    runs-on: macos-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-macos-stable-3.24.1-x64'
          cache-path: '${{ runner.tool_cache }}/flutter-macos-stable-3.24.1-x64-hash'
          channel: 'stable'
          flutter-version: '3.24.1'
      - name: build-web-with-wasm
        run: |
          flutter pub get
          flutter build web --release --wasm

      - name: Install-firebase-tools
        uses: actions/setup-node@v4
        with:
          node-version: "21.2.0"
      - run: npm install -g firebase-tools@11.0.1
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JULIOTATIAPP }}'
          channelId: live
          projectId: juliotatiapp
