name: 🧹 Sort intl Json
on:
  workflow_call:

jobs:
  sort-intl-json-content:
    runs-on: macos-latest
    steps:
      - name: setup-repo
        uses: actions/checkout@v4
      - name: sort-files-content
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/functions.sh"
          chmod +x "${GITHUB_WORKSPACE}/scripts/sort_intl_file_content.sh"
          bash "${GITHUB_WORKSPACE}/scripts/sort_intl_file_content.sh"
