name: 🧹 Sort intl Json
on:
  workflow_call:

jobs:
  sort-intl-json-contents:
    runs-on: macos-latest
    steps:
      - name: setup-repo
        uses: actions/checkout@v4

      - name: get-scripts
        uses: actions/checkout@v4
        with:
          repository: Juliotati/juliotati_app
          path: scripts
          sparse-checkout: scripts/

      - name: sort-files-contents
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/scripts/all_functions.sh"
          chmod +x "${GITHUB_WORKSPACE}/scripts/scripts/sort_intl_file_contents.sh"
          bash "${GITHUB_WORKSPACE}/scripts/scripts/sort_intl_file_contents.sh"
