name: 🧪 Validate Pubspec
on:
  workflow_call:

jobs:
  validate-pubspec-version:
    runs-on: macos-latest
    steps:
      - name: setup-repo
        uses: actions/checkout@v4
      - name: fetch-base-branch-('${{ github.base_ref }}')
        run: |
          echo "Attempting to fetch base branch: ${{ github.base_ref }}"

          # Fetch the specific base branch from the remote and create a local tracking branch.
          git fetch origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

          # Ensure a local branch 'stable' (or whatever base_ref is) exists and points to the fetched commit
          git branch ${{ github.base_ref }} origin/${{ github.base_ref }}

      - name: verify-pubspec-version
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/scripts/all_functions.sh"
          chmod +x "${GITHUB_WORKSPACE}/scripts/scripts/validate_pubspec_version.sh"
          bash "${GITHUB_WORKSPACE}/scripts/scripts/validate_pubspec_version.sh"
#          "${GITHUB_WORKSPACE}/pubspec.yaml" "${GITHUB_WORKSPACE}/pubspec.lock" "${GITHUB_WORKSPACE}/scripts/scripts/pubspec_version.txt" "${{ github.base_ref }}"
